In [14]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import copy
import math
from tkinter import *

In [19]:
def flat(list1):
    for i in list1:
        for j in i:
            if (j != 1 and j != 0):
                return False
    return True
def match(img, ker):
    if img == ker:
        return True
    else:
        return False
    
def oneD(nested):
    flat = [x for sublist in nested for x in sublist]
    return flat
def sub(ziped):
    ret = []
    for i in ziped:
        ret.append(i[0]-i[1])
    return ret
def erosion(image,kernel,a,b):
    ker = kernal.tolist()
    imgL = image.tolist()
    img_x, img_y = image.shape
    kernl_x, kernl_y = kernel.shape
    result = copy.deepcopy(image)
    for i in range(1,(img_x)-int(len(kernel)/2)):
        for j in range(1,(img_y)-int(len(kernel)/2)):
            array = []
            for s in range(-a,a+1):
                for t in range(-b,b+1):
                    array.append(image[i+s,j+t])
            if(flat(kernel)):
                if(flat(imgL)):
#                     print("kernal is flat and image is binary")
                    if(match(array,ker)): #if any one element matched it will write 1 on its place
                        result[i,j] = 1
                    else:
                        result[i,j] = 0
                else:
#                     print("kernal is flat and image is grey scale")
                    mini = min(array) # maximum number from the kernal will be placed on the interest point
                    result[i,j] = mini
            else:
#                 print("kernal is non flat")
                ziped =  zip(array,oneD(ker))#subtracting kenal and window elements of image
                mini = min(sub(ziped))
                result[i,j] = mini
                

                
    return result
def histogram(img):
    plt.hist(img.ravel(),256,[0,256]) 
    plt.plot
    plt.show()

    

In [23]:
array1 = [1,1,1]
array2 = [1,2,1]
array3 = [1,1,1]
kernal = np.array([array1,array2,array3])

ker = kernal.tolist()
array1 = [1,2,3,4,5]
array2 = [6,7,8,9,10]
array3 = [11,12,13,14,15]
array4 = [16,17,18,19,20]
array5 = [21,22,23,24,25]
# array1 = [1,1,1,0,1]
# array2 = [1,1,1,0,1]
# array3 = [1,0,0,1,1]
# array4 = [0,0,1,1,0]
# array5 = [1,0,1,0,1]

image = np.matrix([array1,array2,array3,array4,array5])
# histogram(white_bars)



# white_bars = cv2.imread("/home/ahmed/Downloads/dip/DIP_A1_Fall2019/White-Bars.png")
# white_bars = cv2.cvtColor(white_bars, cv2.COLOR_BGR2GRAY)
# plt.imshow(white_bars,cmap="gray")
# plt.show()
# histogram(white_bars)
# print(white_bars)
a = 1
b = 1
print("the kernal is: ")
print(kernal)
print("the image is")
print(image)
result = erosion(image,kernal,a,b)
# plt.imshow(result.astype(np.uint8),cmap='gray')
# plt.show()
print("result")
print(result)
# histogram(white_bars)
# histogram(result)

the kernal is: 
[[1 1 1]
 [1 2 1]
 [1 1 1]]
the image is
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
result
[[ 1  2  3  4  5]
 [ 6  0  1  2 10]
 [11  5  6  7 15]
 [16 10 11 12 20]
 [21 22 23 24 25]]
