In [22]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import copy
import math
from tkinter import *

In [32]:
def flat(list1):
    for i in list1:
        for j in i:
            if (j != 1 and j != 0):
                return False
    return True
def match(img, ker):
    counter = 0
    for i in range(len(ker)):
        for j in range(len(ker)):
            if img[counter] == ker[i][j]:
                counter+=1
                return True
            else:
                counter+=1
    else:
        return False
    
def oneD(nested):
    flat = [x for sublist in nested for x in sublist]
    return flat

def dilation(image,kernel,a,b):
    ker = kernal.tolist()
    imgL = image.tolist()
    img_x, img_y = image.shape
    kernl_x, kernl_y = kernel.shape
    result = copy.deepcopy(image)
    for i in range(1,(img_x-1)-int(len(kernel)/2)):
        for j in range(1,(img_y-1)-int(len(kernel)/2)):
            array = []
            for s in range(-a,a+1):
                for t in range(-b,b+1):
                    array.append(image[i+s,j+t])
            if(flat(kernel)):
                if(flat(imgL)):
#                     print("kernal is flat and image is binary")
                    if(match(array,ker)): #if any one element matched it will write 1 on its place
                        result[i,j] = 1
                    else:
                        result[i,j] = 0
                else:
#                     print("kernal is flat and image is grey scale")
                    maxi = max(array) # maximum number from the kernal will be placed on the interest point
                    result[i,j] = maxi
            else:
#                 print("kernal is non flat")
                res_list = [sum(i) for i in zip(array,oneD(ker))]  #adding kenal and window elements of image
                maxi = max(res_list)
                result[i,j] = maxi
            
    return result


In [33]:

def matchE(img, ker):
    if img == ker:
        return True
    else:
        return False
    
def sub(ziped):
    ret = []
    for i in ziped:
        ret.append(i[0]-i[1])
    return ret
def erosion(image,kernel,a,b):
    print(kernel)
    ker = kernal.tolist()
    imgL = image.tolist()
    img_x, img_y = image.shape
    print(image.shape)
    kernl_x, kernl_y = kernel.shape
    print(int(len(kernal)/2))
    result = copy.deepcopy(image)
    for i in range(1,(img_x-1)-int(len(kernel)/2)):
        for j in range(1,(img_y-1)-int(len(kernel)/2)):
            array = []
            for s in range(-a,a+1):
                for t in range(-b,b+1):
                    array.append(image[i+s,j+t])
            if(flat(kernel)):
                if(flat(imgL)):
#                     print("kernal is flat and image is binary")
                    if(matchE(array,ker)): #if any one element matched it will write 1 on its place
                        result[i,j] = 1
                    else:
                        result[i,j] = 0
                else:
#                     print("kernal is flat and image is grey scale")
                    mini = min(array) # maximum number from the kernal will be placed on the interest point
                    result[i,j] = mini
            else:
#               print("kernal is non flat")
                ziped =  zip(array,oneD(ker))#subtracting kenal and window elements of image
                mini = min(sub(ziped))
                result[i,j] = mini
                

                
    return result

In [43]:
array1 = [1,1,1]
array2 = [1,1,1]
array3 = [1,1,1]
kernal = np.array([array1,array2,array3])

ker = kernal.tolist()
# array1 = [1,2,3,4,5]
# array2 = [6,7,8,9,10]
# array3 = [11,12,13,14,15]
# array4 = [16,17,18,19,20]
# array5 = [21,22,23,24,25]
array1 = [1,1,1,0,1]
array2 = [1,1,1,0,1]
array3 = [1,0,0,1,1]
array4 = [0,0,1,1,0]
array5 = [1,0,1,0,1]

image = np.matrix([array1,array2,array3,array4,array5])
print("image")
print(image)
print("kernal")
a = 1
b = 1
result = erosion(image,kernal,a,b)
print("applied erosion first")
print(result)
f_result = dilation(result,kernal,a,b)
print("second applied dilation")
print(f_result)

image
[[1 1 1 0 1]
 [1 1 1 0 1]
 [1 0 0 1 1]
 [0 0 1 1 0]
 [1 0 1 0 1]]
kernal
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(5, 5)
1
applied erosion first
[[1 1 1 0 1]
 [1 0 0 0 1]
 [1 0 0 1 1]
 [0 0 1 1 0]
 [1 0 1 0 1]]
second applied dilation
[[1 1 1 0 1]
 [1 1 1 0 1]
 [1 1 1 1 1]
 [0 0 1 1 0]
 [1 0 1 0 1]]


In [44]:
print("image")
print(image)
print("kernal")
print(kernal)
result = dilation(image,kernal,a,b)
print("applied dilation first")
print(result)
f_result = erosion(result,kernal,a,b)
print("second applied erosion")
print(f_result)

image
[[1 1 1 0 1]
 [1 1 1 0 1]
 [1 0 0 1 1]
 [0 0 1 1 0]
 [1 0 1 0 1]]
kernal
[[1 1 1]
 [1 1 1]
 [1 1 1]]
applied dilation first
[[1 1 1 0 1]
 [1 1 1 0 1]
 [1 1 1 1 1]
 [0 0 1 1 0]
 [1 0 1 0 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(5, 5)
1
second applied erosion
[[1 1 1 0 1]
 [1 0 0 0 1]
 [1 0 0 1 1]
 [0 0 1 1 0]
 [1 0 1 0 1]]
